### PR TITLE
[DPE-3067] Changes following up entrypoint service refactoring

### PR DESCRIPTION
**Pull request by deusebio**

### CODE REVIEW

**Review by welpaolo — DISMISSED** [review]
Looks good to me!

**Review by cjdcordeiro — APPROVED** [review]
nice. looking tidier now :)

LGTM

out of curiosity, are you moving Jupyter to its own separate image?

**Comment by deusebio** [comment]
Yes, indeed! But this is going to be a separate task.

**Review by welpaolo — APPROVED** [review]
LGTM

**Review by grobbie — APPROVED** [review]
looks good thanks

**Pull request merged**
